### PR TITLE
React >= 15.5.0 support

### PR DESCRIPTION
**Pull request by OscarBarrett**
- Use [prop-types](https://github.com/reactjs/prop-types) module instead of `React.PropTypes`, standardised usage
- Updated react-docgen version constraint
- Updated yarn lockfiles

Addresses https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings

### CODE REVIEW

**Comment by jarzuaga** [comment]
When is this going to be release?

**Comment by imtoo** [comment]
@jarzuaga It's already released.

**Comment by OscarBarrett** [comment]
It's on npm, however GitHub doesn't have a tag/release for 0.4.3 yet.

BTW, I've noticed some other dependencies are giving deprecation warnings but haven't been updated yet. See below for relevant issues.

- `react-copy-to-clipboard`: https://github.com/nkbt/react-copy-to-clipboard/issues/55
- `radium`: https://github.com/FormidableLabs/radium/issues/895

**Comment by imtoo** [comment]
@OscarBarrett I've added new release on Github. We'll take a look on these warnings later, thanks for pointing it out.

**Comment by jarzuaga** [comment]
@OscarBarrett thanks

**Pull request merged**
