### PR TITLE
Add design responsivity

### PR DESCRIPTION
**Pull request by imtoo**

### CODE REVIEW

**Comment by imtoo** [comment]
@ondrejbartas I had problems with fuzzy to ignore blank spaces. Can you look at it? Thanks.

**Comment by ondrejbartas** [comment]
@imtoo it is just about what you are sending to fuzzy search. You can remove blank spaces before you are sending searched text to fuzzy search 😄

**Comment by ondrejbartas** [comment]
@imtoo pls ask somebody to fix testsfor it ( @honzabrecka )

**Comment by imtoo** [comment]
@ondrejbartas Yes, I know that. But as a result in AllComponentsPreview you get what you searched in. So there are names of components without spaces ```ExampleComponentsButton``` instead of ```ExampleComponents Button```, I think we would like the example with spaces.

I'll ask @honzabrecka

**Comment by imtoo** [comment]
@ondrejbartas Tests fixed.

**Pull request merged**
