### PR TITLE
Rewrite Application to be able to work inline directly from component

### PR DESCRIPTION
**Pull request by ondrejbartas**

### CODE REVIEW

**Comment by aaronjensen** [comment]
Are there plans to finish this and the CLI (which I'm guessing gets rid of the gulp dependency?)

**Comment by ondrejbartas** [comment]
@aaronjensen this PR works. But there is one issue which I was not able to fix. When you are using Hot Reload, your components code get reloaded, but propTypes are not updated, so when you change pros, you needs to reload whole page :( which I don't like. I am still thinking about workarounds ...

**Comment by badabam** [comment]
Any news on this?

**Comment by imtoo** [comment]
Not yet.

**Comment by imtoo** [comment]
Temporarily closed

**Pull request closed without merging**
